version: "3"
services:
  mongodb-container-crypto:
    image: mongo:latest
    container_name: "mongodb-container-crypto"
    ports:
      - 27017:27017
  crypro-recommendation-service:
    image: crypro-recommendation-service
    container_name: crypro-recommendation-service
    ports:
      - 8080:8080
    links:
      - mongodb-container-crypto
      
  cache:
    image: redis:6.2
    container_name: my-redis-crypto
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
      
      